
apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo-pod
  namespace: default
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Hello from EBS PVC at $(date)" > /data/hello.txt;
          sleep 3600
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: ebs-claim

